### ISSUE TITLE
Can't connect to jellyfin

### ISSUE THREAD

**Issue by kabo** [jellyfin/jellyfin-android#329]
**Describe the bug**

I can't connect to my jellyfin server.

**To Reproduce**

1. Start app  
![Screenshot_20210327-130624](https://user-images.githubusercontent.com/357601/112703964-c05b2180-8efd-11eb-92d1-26871eb510d2.png)
2. Click choose server  
![Screenshot_20210327-130632](https://user-images.githubusercontent.com/357601/112703983-d1a42e00-8efd-11eb-9e2a-2b626568b19f.png)
3. Click the server
![Screenshot_20210327-130640](https://user-images.githubusercontent.com/357601/112704000-e7195800-8efd-11eb-95e6-87a63f58044f.png)

**Expected behavior**

To be asked for my credentials

**Logs**

Nothing shows up in the server logs

**Screenshots**

**System (please complete the following information):**
 - App version: 2.2.3
 - Android version: Android 11
 - Device manufacturer and model: Google Pixel 2XL
 - Jellyfin server version: 10.7.1-1
 - The type of video player implementation used: ???

**Additional context**

Connecting via the browser from my computer and my phone both work fine.

**Comment by nielsvanvelzen** [comment]
Is your server hosted in a virtualized environment? (Docker container or Windows with Hyper-V enabled)
Looks like the auto-discovery address is sending a virtual ip.

**Comment by kabo** [comment]
My local network is `172.22.16.1/21`. I'm running jellyfin in an LXC container, but it gets its IP directly from the router. In the browser it works fine, it's only the android app that's having this issue.

**Comment by nielsvanvelzen** [comment]
Okay that's weird, did you try connecting directly instead of using the discovery feature?

**Comment by kabo** [comment]
Yeah, makes no difference.

**Comment by dillbyrne** [comment]
Hi all, a big thanks for the hard work.

I'm experiencing the exact same issue. I see no logs on the webserver.
I'm using a lets encrypt cert with an nginx reverse proxy. No issues using a web browser on the desktop or mobile. its just the android app.

I can see the DNS is rewritten correctly my adguard container so there is a DNS request made to my server but for some reason the app fails to initiate a connection. This setup was working fine prior to the update and still works in all browsers, Kodi, VLC etc so I'm not inclined to say its the issue. I have also tried the ip directly but still the same.
My server is TLS 1.3 only if that makes a difference but android 10 has support for it. 

I'm also using the format https://server.name/jellyfin

The app was working fine prior to 10.7.x update.

App version: 2.2.3
Android version: Android 10
Device manufacturer and model: Samsung J3
Jellyfin server version: 10.7.1 linuxserver container
The type of video player implementation used: ???

Thanks again all

**Comment by kabo** [comment]
I ran adb logcat when trying to connect to my server, perhaps this helps?

Server version: 10.7.5
Jellyfin app version: 2.3.0-beta.1 (F-droid)
Device: Google Pixel 4a 5G
Andriod version: 11

```
$ adb shell ps | grep jellyfin
u0_a161       30891    837 248446132 237308 0                 0 S org.jellyfin.mobile
$ adb logcat | grep 30891
06-03 23:03:19.960   837   837 D Zygote  : Forked child process 30891
06-03 23:03:19.962 30891 30891 W Zygote  : Can't access app profile directory: /data_mirror/cur_profiles/0/org.jellyfin.mobile
06-03 23:03:19.963  1662  1719 I ActivityManager: Start proc 30891:org.jellyfin.mobile/u0a161 for pre-top-activity {org.jellyfin.mobile/org.jellyfin.mobile.MainActivity}
06-03 23:03:19.969 30891 30891 E jellyfin.mobil: Not starting debugger since process cannot load the jdwp agent.
06-03 23:03:20.028 30891 30891 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10161 <<<<<<
06-03 23:03:20.030 30891 30891 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.profilebootclasspath"
06-03 23:03:20.030 30891 30891 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.enable_apex_image"
06-03 23:03:20.030 30891 30891 I AndroidRuntime: Using default boot image
06-03 23:03:20.030 30891 30891 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.disable_lock_profiling"
06-03 23:03:20.030 30891 30891 I AndroidRuntime: Leaving lock profiling enabled
06-03 23:03:20.031 30891 30891 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.enable_generational_cc"
06-03 23:03:20.026 30891 30891 W jellyfin.mobile: type=1400 audit(0.0:20865): avc: denied { read } for name="u:object_r:device_config_runtime_native_boot_prop:s0" dev="tmpfs" ino=10614 scontext=u:r:untrusted_app:s0:c161,c256,c512,c768 tcontext=u:object_r:device_config_runtime_native_boot_prop:s0 tclass=file permissive=0 app=org.jellyfin.mobile
06-03 23:03:20.026 30891 30891 I chatty  : uid=10161(org.jellyfin.mobile) identical 2 lines
06-03 23:03:20.026 30891 30891 W jellyfin.mobile: type=1400 audit(0.0:20868): avc: denied { read } for name="u:object_r:device_config_runtime_native_boot_prop:s0" dev="tmpfs" ino=10614 scontext=u:r:untrusted_app:s0:c161,c256,c512,c768 tcontext=u:object_r:device_config_runtime_native_boot_prop:s0 tclass=file permissive=0 app=org.jellyfin.mobile
06-03 23:03:20.030 30891 30891 W jellyfin.mobile: type=1400 audit(0.0:20869): avc: denied { lock } for path="/apex/com.android.art/javalib/arm64/boot.art" dev="dm-12" ino=139 scontext=u:r:untrusted_app:s0:c161,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=org.jellyfin.mobile
06-03 23:03:20.100 30891 30891 D org.jellyfin.mobile: Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
06-03 23:03:20.100 30891 30891 D org.jellyfin.mobile: I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt66l.dat
06-03 23:03:20.113 30891 30891 W org.jellyfin.mobile: JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
06-03 23:03:20.118 30891 30891 D AndroidRuntime: Calling main entry com.android.internal.os.ExecInit
06-03 23:03:20.118 30891 30891 D Zygote  : begin preload
06-03 23:03:20.118 30891 30891 I Zygote  : Calling ZygoteHooks.beginPreload()
06-03 23:03:20.121 30891 30891 I Zygote  : Preloading shared libraries...
06-03 23:03:20.189 30891 30891 I Zygote  : Called ZygoteHooks.endPreload()
06-03 23:03:20.198 30891 30891 I Zygote  : Installed AndroidKeyStoreProvider in 10ms.
06-03 23:03:20.198 30891 30891 D Zygote  : end preload
06-03 23:03:20.212 30891 30891 W org.jellyfin.mobile: Insufficient pre-allocated space to mmap vdex.
06-03 23:03:20.228 30891 30891 I PackageParser: Skipping target and overlay pair android and /product/overlay/FrameworkOverlayG6QU3.apk: overlay ignored due to required system property: ro.boot.hardware.sku with value: G6QU3
06-03 23:03:20.230 30891 30891 I PackageParser: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayG025H.apk: overlay ignored due to required system property: ro.boot.hardware.sku with value: G025H
06-03 23:03:20.236 30891 30891 I PackageParser: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayG025I.apk: overlay ignored due to required system property: ro.boot.hardware.sku with value: G025I
06-03 23:03:20.239 30891 30891 I PackageParser: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayG6QU3.apk: overlay ignored due to required system property: ro.boot.hardware.sku with value: G6QU3
06-03 23:03:20.245 30891 30891 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
06-03 23:03:20.246 30891 30891 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
06-03 23:03:20.278 30891 30920 D libEGL  : loaded /vendor/lib64/egl/libEGL_adreno.so
06-03 23:03:20.282 30891 30920 D libEGL  : loaded /vendor/lib64/egl/libGLESv1_CM_adreno.so
06-03 23:03:20.285 30891 30920 D libEGL  : loaded /vendor/lib64/egl/libGLESv2_adreno.so
06-03 23:03:20.329 30891 30891 I WebViewFactory: Loading app.vanadium.webview version 91.0.4472.77 (code 447207734)
06-03 23:03:20.332 30891 30891 I org.jellyfin.mobile: The ClassLoaderContext is a special shared library.
06-03 23:03:20.332 30891 30891 D nativeloader: classloader namespace configured for unbundled product apk. library_path=/product/app/TrichromeWebView/lib/arm64:/product/app/TrichromeWebView/TrichromeWebView.apk!/lib/arm64-v8a:/product/app/TrichromeLibrary/TrichromeLibrary.apk!/lib/arm64-v8a:/product/lib64:/system/product/lib64
06-03 23:03:20.335 30891 30891 I org.jellyfin.mobile: The ClassLoaderContext is a special shared library.
06-03 23:03:20.336 30891 30891 D nativeloader: classloader namespace configured for unbundled product apk. library_path=/product/app/TrichromeWebView/lib/arm64:/product/app/TrichromeWebView/TrichromeWebView.apk!/lib/arm64-v8a:/product/app/TrichromeLibrary/TrichromeLibrary.apk!/lib/arm64-v8a:/product/lib64:/system/product/lib64
06-03 23:03:20.337 30891 30891 E WebViewLibraryLoader: can't load with relro file; address space not reserved
06-03 23:03:20.362 30891 30891 I cr_LibraryLoader: Loaded native library version number "91.0.4472.77"
06-03 23:03:20.362 30891 30891 I cr_CachingUmaRecorder: Flushed 4 samples from 4 histograms.
06-03 23:03:20.461 30891 30918 I AdrenoGLES-0: QUALCOMM build                   : 4783c89, I46ff5fc46f
06-03 23:03:20.461 30891 30918 I AdrenoGLES-0: Build Date                       : 11/30/20
06-03 23:03:20.461 30891 30918 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.31.04.01
06-03 23:03:20.461 30891 30918 I AdrenoGLES-0: Local Branch                     : QPR2
06-03 23:03:20.461 30891 30918 I AdrenoGLES-0: Remote Branch                    :
06-03 23:03:20.461 30891 30918 I AdrenoGLES-0: Remote Branch                    :
06-03 23:03:20.461 30891 30918 I AdrenoGLES-0: Reconstruct Branch               :
06-03 23:03:20.461 30891 30918 I AdrenoGLES-0: Build Config                     : S P 10.0.4 AArch64
06-03 23:03:20.461 30891 30918 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
06-03 23:03:20.467 30891 30918 I AdrenoGLES-0: PFP: 0x016dd090, ME: 0x00000000
06-03 23:03:20.473 30891 30918 W AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
06-03 23:03:20.473 30891 30918 W AdrenoUtils: <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
06-03 23:03:20.524 30891 30891 W System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
06-03 23:03:20.524 30891 30891 W System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
06-03 23:03:20.524 30891 30891 W System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
06-03 23:04:14.897 30891 30918 D OpenGLRenderer: endAllActiveAnimators on 0xb400de19ddc21d00 (AlertController$RecycleListView) with handle 0xb400de07e59bce10
06-03 23:04:14.910 30891 30891 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
06-03 23:04:14.950 30891 30891 W IInputConnectionWrapper: requestCursorAnchorInfo on inactive InputConnection
06-03 23:04:15.105 30891 30891 W ConnectFragment: Recommended server did not contain system information!
```

**Comment by nielsvanvelzen** [comment]
Upgrade to the second or third beta, bug is already fixed. (See #366)

**Comment by kabo** [comment]
Still not working with beta 3 though.

<img width="540" alt="Screenshot_20210611-230100" src="https://user-images.githubusercontent.com/357601/121677515-13f70780-cb0a-11eb-8380-d3913f618f17.png">

```
$ adb shell ps | grep jellyfin
u0_a161       18080    837 247222152 234612 0                 0 S org.jellyfin.mobile
$ adb logcat | grep 18080
06-11 23:00:19.190   837   837 D Zygote  : Forked child process 18080
06-11 23:00:19.195 18080 18080 W Zygote  : Can't access app profile directory: /data_mirror/cur_profiles/0/org.jellyfin.mobile
06-11 23:00:19.199  1662  1719 I ActivityManager: Start proc 18080:org.jellyfin.mobile/u0a161 for pre-top-activity {org.jellyfin.mobile/org.jellyfin.mobile.MainActivity}
06-11 23:00:19.205 18080 18080 E jellyfin.mobil: Not starting debugger since process cannot load the jdwp agent.
06-11 23:00:19.394 18080 18080 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10161 <<<<<<
06-11 23:00:19.403 18080 18080 W jellyfin.mobile: type=1400 audit(0.0:152347): avc: denied { read } for name="u:object_r:device_config_runtime_native_boot_prop:s0" dev="tmpfs" ino=10614 scontext=u:r:untrusted_app:s0:c161,c256,c512,c768 tcontext=u:object_r:device_config_runtime_native_boot_prop:s0 tclass=file permissive=0 app=org.jellyfin.mobile
06-11 23:00:19.403 18080 18080 I chatty  : uid=10161(org.jellyfin.mobile) identical 2 lines
06-11 23:00:19.403 18080 18080 W jellyfin.mobile: type=1400 audit(0.0:152350): avc: denied { read } for name="u:object_r:device_config_runtime_native_boot_prop:s0" dev="tmpfs" ino=10614 scontext=u:r:untrusted_app:s0:c161,c256,c512,c768 tcontext=u:object_r:device_config_runtime_native_boot_prop:s0 tclass=file permissive=0 app=org.jellyfin.mobile
06-11 23:00:19.404 18080 18080 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.profilebootclasspath"
06-11 23:00:19.404 18080 18080 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.enable_apex_image"
06-11 23:00:19.404 18080 18080 I AndroidRuntime: Using default boot image
06-11 23:00:19.404 18080 18080 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.disable_lock_profiling"
06-11 23:00:19.404 18080 18080 I AndroidRuntime: Leaving lock profiling enabled
06-11 23:00:19.404 18080 18080 E libc    : Access denied finding property "persist.device_config.runtime_native_boot.enable_generational_cc"
06-11 23:00:19.406 18080 18080 W jellyfin.mobile: type=1400 audit(0.0:152351): avc: denied { lock } for path="/apex/com.android.art/javalib/arm64/boot.art" dev="dm-12" ino=139 scontext=u:r:untrusted_app:s0:c161,c256,c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=org.jellyfin.mobile
06-11 23:00:19.539 18080 18080 D org.jellyfin.mobile: Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
06-11 23:00:19.540 18080 18080 D org.jellyfin.mobile: I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt66l.dat
06-11 23:00:19.560 18080 18080 W org.jellyfin.mobile: JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
06-11 23:00:19.569 18080 18080 D AndroidRuntime: Calling main entry com.android.internal.os.ExecInit
06-11 23:00:19.569 18080 18080 D Zygote  : begin preload
06-11 23:00:19.569 18080 18080 I Zygote  : Calling ZygoteHooks.beginPreload()
06-11 23:00:19.575 18080 18080 I Zygote  : Preloading shared libraries...
06-11 23:00:19.785 18080 18080 I Zygote  : Called ZygoteHooks.endPreload()
06-11 23:00:19.799 18080 18080 I Zygote  : Installed AndroidKeyStoreProvider in 14ms.
06-11 23:00:19.799 18080 18080 D Zygote  : end preload
06-11 23:00:19.862 18080 18080 I PackageParser: Skipping target and overlay pair android and /product/overlay/FrameworkOverlayG6QU3.apk: overlay ignored due to required system property: ro.boot.hardware.sku with value: G6QU3
06-11 23:00:19.870 18080 18080 I PackageParser: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayG025H.apk: overlay ignored due to required system property: ro.boot.hardware.sku with value: G025H
06-11 23:00:19.894 18080 18080 I PackageParser: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayG025I.apk: overlay ignored due to required system property: ro.boot.hardware.sku with value: G025I
06-11 23:00:19.903 18080 18080 I PackageParser: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayG6QU3.apk: overlay ignored due to required system property: ro.boot.hardware.sku with value: G6QU3
06-11 23:00:19.918 18080 18080 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
06-11 23:00:19.919 18080 18080 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
06-11 23:00:19.954 18080 18109 D libEGL  : loaded /vendor/lib64/egl/libEGL_adreno.so
06-11 23:00:19.972 18080 18109 D libEGL  : loaded /vendor/lib64/egl/libGLESv1_CM_adreno.so
06-11 23:00:19.975 18080 18109 D libEGL  : loaded /vendor/lib64/egl/libGLESv2_adreno.so
06-11 23:00:19.982 18080 18080 I WebViewFactory: Loading app.vanadium.webview version 91.0.4472.77 (code 447207734)
06-11 23:00:19.993 18080 18080 I org.jellyfin.mobile: The ClassLoaderContext is a special shared library.
06-11 23:00:19.996 18080 18080 D nativeloader: classloader namespace configured for unbundled product apk. library_path=/product/app/TrichromeWebView/lib/arm64:/product/app/TrichromeWebView/TrichromeWebView.apk!/lib/arm64-v8a:/product/app/TrichromeLibrary/TrichromeLibrary.apk!/lib/arm64-v8a:/product/lib64:/system/product/lib64
06-11 23:00:20.016 18080 18080 I org.jellyfin.mobile: The ClassLoaderContext is a special shared library.
06-11 23:00:20.017 18080 18080 D nativeloader: classloader namespace configured for unbundled product apk. library_path=/product/app/TrichromeWebView/lib/arm64:/product/app/TrichromeWebView/TrichromeWebView.apk!/lib/arm64-v8a:/product/app/TrichromeLibrary/TrichromeLibrary.apk!/lib/arm64-v8a:/product/lib64:/system/product/lib64
06-11 23:00:20.019 18080 18080 E WebViewLibraryLoader: can't load with relro file; address space not reserved
06-11 23:00:20.050 18080 18080 I cr_LibraryLoader: Loaded native library version number "91.0.4472.77"
06-11 23:00:20.050 18080 18080 I cr_CachingUmaRecorder: Flushed 4 samples from 4 histograms.
06-11 23:00:20.131 18080 18107 I AdrenoGLES-0: QUALCOMM build                   : 4783c89, I46ff5fc46f
06-11 23:00:20.131 18080 18107 I AdrenoGLES-0: Build Date                       : 11/30/20
06-11 23:00:20.131 18080 18107 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.31.04.01
06-11 23:00:20.131 18080 18107 I AdrenoGLES-0: Local Branch                     : QPR2
06-11 23:00:20.131 18080 18107 I AdrenoGLES-0: Remote Branch                    :
06-11 23:00:20.131 18080 18107 I AdrenoGLES-0: Remote Branch                    :
06-11 23:00:20.131 18080 18107 I AdrenoGLES-0: Reconstruct Branch               :
06-11 23:00:20.131 18080 18107 I AdrenoGLES-0: Build Config                     : S P 10.0.4 AArch64
06-11 23:00:20.131 18080 18107 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
06-11 23:00:20.140 18080 18107 I AdrenoGLES-0: PFP: 0x016dd090, ME: 0x00000000
06-11 23:00:20.180 18080 18107 W AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
06-11 23:00:20.180 18080 18107 W AdrenoUtils: <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
06-11 23:00:20.219 18080 18080 W System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
06-11 23:00:20.219 18080 18080 W System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
06-11 23:00:20.219 18080 18080 W System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
06-11 23:00:40.674 18080 18107 D OpenGLRenderer: endAllActiveAnimators on 0xb400c318bfbef900 (AlertController$RecycleListView) with handle 0xb400c30715323f60
06-11 23:00:40.730 18080 18080 W IInputConnectionWrapper: requestCursorAnchorInfo on inactive InputConnection
```

**Comment by Maxr1998** [comment]
The logs unfortunately don't contain any hints on what's wrong. Is the displayed port correct?

**Comment by kabo** [comment]
Yeah the port is right, and it's a self signed cert. I have installed the cert on my device, but I realize the name in the cert doesn't actually match... could that be an issue?

**Comment by Maxr1998** [comment]
That could definitely be the reason. Android only accepts certificates that are trusted, and has to match with the hostname.

**Comment by kabo** [comment]
OK, I managed to connect! Followed this guide to create a CA which I could then create a jellyfin cert from. Had to change `DNS.1 = ...` to `IP.1 = ...`

https://deliciousbrains.com/ssl-certificate-authority-for-local-https-development/

Installed the CA on my phone. Connected!

**Comment by kabo** [comment]
Well... sort of. I can connect, but it won't accept my password.

adb logcat
```
06-13 13:14:17.513  5477  5477 W cr_AwAutofillManager: Autofill is disabled: AutofillManager isn't available in given Context.
06-13 13:14:18.603  5477  5477 W cr_AwAutofillManager: Autofill is disabled: AutofillManager isn't available in given Context.
06-13 13:14:20.530  5477  5477 W cr_AwAutofillManager: Autofill is disabled: AutofillManager isn't available in given Context.
06-13 13:14:26.679  5477  5477 I WebView : returning instance from getOrAddApiClient, https://172.xx.xx.xx:8920/web/main.4b4b736dbefe7c3a90ec.bundle.js (2)
06-13 13:14:26.679  5477  5477 I WebView : Requesting url without automatic networking: https://172.xx.xx.xx:8920/Users/authenticatebyname, https://172.xx.xx.xx:8920/web/main.4b4b736dbefe7c3a90ec.bundle.js (2)
06-13 13:14:26.764  5477  5477 E Method  : Received WebView HTTP 400 error: null
06-13 13:15:26.669  5477  5477 W IInputConnectionWrapper: requestCursorAnchorInfo on inactive InputConnection
06-13 13:15:26.670  5477  5477 W IInputConnectionWrapper: requestCursorAnchorInfo on inactive InputConnection
```

Server logs
```
Jun 13 01:14:26 jellyfin jellyfin[9447]: [01:14:26] [INF] Authentication request for manager has succeeded.
Jun 13 01:14:26 jellyfin jellyfin[9447]: [01:14:26] [INF] Current/Max sessions for user manager: 1/0
Jun 13 01:14:26 jellyfin jellyfin[9447]: [01:14:26] [INF] Reissuing access token: 5ed91565c0554efa9b05d319c8d48ee4
Jun 13 01:14:26 jellyfin jellyfin[9447]: [01:14:26] [ERR] Error processing request. URL POST /Users/authenticatebyname.
Jun 13 01:14:26 jellyfin jellyfin[9447]: System.ArgumentNullException: Value cannot be null. (Parameter 'appName')
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Emby.Server.Implementations.Session.SessionManager.LogSessionActivity(String appName, String appVersion, String deviceId, String deviceName, String remoteEndPoint, User user)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Jellyfin.Api.Controllers.UserController.AuthenticateUserByName(AuthenticateUserByName request)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at lambda_method779(Closure , Object )
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
Jun 13 01:14:26 jellyfin jellyfin[9447]:    at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

![Screenshot_20210613-131713](https://user-images.githubusercontent.com/357601/121792502-cb466800-cc49-11eb-8279-138da36afd21.png)

**Comment by kabo** [comment]
Ah, running in to this issue now
https://github.com/jellyfin/jellyfin/issues/6081

**Comment by Extarys** [comment]
I had to disconnect from the app and when I tried logging in I had this issue. I tried both apk from the 2.3.0-beta4 on Android and I get the following:

```
[INF] [67] Emby.Server.Implementations.Session.SessionManager: Reissuing access token: "3af26ab58311429baf13cbe89b2cce06"
[2021-07-01 08:49:33.908 -04:00] [ERR] [67] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/Users/authenticatebyname".
System.ArgumentNullException: Value cannot be null. (Parameter 'appName')
   at Emby.Server.Implementations.Session.SessionManager.LogSessionActivity(String appName, String appVersion, String deviceId, String deviceName, String remoteEndPoint, User user)
   at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
   at Jellyfin.Api.Controllers.UserController.AuthenticateUserByName(AuthenticateUserByName request)
   at lambda_method1227(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)

```
I started by wiping cache/data and reinstalling the beta3. Then I tried both open and proprietary beta4.

Sorry for my short reply I'm on mobile/away.

**Comment by nielsvanvelzen** [comment]
Why are you using an outdated beta version? Go back to stable (2.2.x) or use the latest beta (2.3.0-beta.6 right now).

**Comment by Extarys** [comment]
Oh thanks! I followed a link to the release and thought beta4 was the latest. Totally my mistake! 🙄😛
Going to the release page right now hahaha

**Comment by Extarys** [comment]
@nielsvanvelzen ahh damn it works 😅

Thank you so much. I feel stupid. On mobile I thought beta 4 was the latest. You are my hero.

Any idea why the latest on fdroid is beta3?

**Comment by nielsvanvelzen** [comment]
F-Droid has beta.6: https://f-droid.org/en/packages/org.jellyfin.mobile/

**Comment by Extarys** [comment]
Oh strange it seems both my aurora droid and my fdroid app are bugged.. 😑😡
