### ISSUE TITLE
Error when trying to enter the server in the beta of Jellyfin for Android

### ISSUE THREAD

**Issue by JulioNahum** [jellyfin/jellyfin-android#366]
**Describe the bug**
When putting the address of the server an error appears saying that I update to a more updated version of my server. But I have version 10.7.5, the last one released. And the exact same thing happens to many users. I hope they can fix it as quickly as possible

**Screenshots**
![photo4945336013492955494](https://user-images.githubusercontent.com/30002132/117356791-87ae5080-ae8a-11eb-8612-0d0610eb39c0.jpg)

**System (please complete the following information):**
 - App version: [2.3.0-beta1]
 - Android version: [Android 10]
 - Device manufacturer and model: [LG k50S]
 - Jellyfin server version: [10.7.5]

**Comment by nielsvanvelzen** [comment]
Thanks for reporting, we're aware of this issue and I'm looking into it. Right now it looks like the app always shows the same error, even when it fails to connect to your server. So the workaround is to doublecheck your input.

**Comment by FazeThree71** [comment]
Confirmed the address is identical to my browser's (in this case, http://192.168.4.44:8096. Also tried http://192.168.4.44:8096/web/index.html). My details: 

TerraMaster F2-221 NAS
Image is jellyfin/jellyfin running in a Docker container 
Version: 10.7.5
Operating System: Linux  (CentOS?)
Architecture: X64

Phone is Pixel 3aXL running Android 11 on the May 5 patch (RQ2A.210505.002). Both -release versions behave the same way for me.

**Comment by kooolarpan** [comment]
I am also encountering the same issue.

**Comment by belpolaris** [comment]
I also am encountering this issue. 10.7.5 server version, using the 'proprietary' apk. Attempted DNS, direct IP input - with and without port or protocol. Same error.

**Comment by solankimihir** [comment]
> Please share the following information so we can identify the issue:
> 
> * Did you add `http://` or `https://` to the address?
Added "http" because that is what I use even in my browser

> * Did you add a port (`:8096`, `:80`)
Port 8086

> * Did you use a baseurl (like `/jellyfin`)
Nope. My URL is http://192.168.0.121:8096
I tried with http://192.168.0.121:8096/jellyfin on browser and the app both, it doesnt work anywhere

> * Did the address end with a slash? (`jellyfin.local/` instead of `jellyfin.local`)
Nope.
Tried doing http://192.168.0.121:8096/ still doesnt work

> * Does opening the exact same address in the browser work?
Nope. In browser, jellyfin-web opens when I type http://192.168.0.121:8096

> * What do you see when you append "/system/info/public" to the URL? (so `http://jellyfin.local/` becomes `http://jellyfin.local/system/info/public`) - you can the server name / local address
On the app, it gives me same error 
"The serer uses an unsupported version. Upgrade to the latest version available at jellyfin.org"
On the browser, I get following lines:
{"LocalAddress":"http://192.168.0.121:8096","ServerName":"NAME-REDACTED","Version":"10.7.5","ProductName":"Jellyfin Server","OperatingSystem":"Linux","Id":"_ID-REDACTED_","StartupWizardCompleted":true}
I have redacted ServerName and ServerID (I am not sure whether its safe to share those. If you need those and are of the opinion that its safe to share, I will update it.

> * Did you install the beta manually (if so, which of the various files?) or via Play Store update?
Tired Manually the "proprietory version" from github release page. It didnt work. So uninstalled and reinstalled from the playstore (I am in beta program). Still doesnt work.


If you need access to my server, I can grant you access through ZeroTier for testing.

**Comment by chrismast** [comment]
I got the same issue.
Tried my IP address plus 8096 port which works in browser whereas getting same error as mentioned by others on the unsupported version.
Also tried via my URL, http and https with same result.
I use the proprietary APK, Jellyfish is latest version via APT installed in an LXC.
Standard Android app (non beta) works fine.

**Comment by eltiel** [comment]
Not sure if this is useful information but I had this problem when I attempted to connect to the server directly i.e. via IP but it worked when I connected via my reverse proxy domain

**Comment by CarlosOlivo** [comment]
The error is in the way the `getRecommendedServers` & `getRecommendedServer` methods work in jellyfin-sdk-kotlin, the problem with these methods is that it does not verify that the chosen candidates are actually accessible.

https://github.com/jellyfin/jellyfin-sdk-kotlin/blob/fe95315460faf3033c705fb264973d93520b784b/jellyfin-core/src/main/kotlin/org/jellyfin/sdk/discovery/DiscoveryService.kt#L79-L100

For example:

> 2021-05-07 22:55:04.823 18417-18417/org.jellyfin.mobile.debug I/ConnectFragment: checkServerUrlAndConnection **http://192.168.1.71:8096**
> 2021-05-07 22:55:04.830 18417-18417/org.jellyfin.mobile.debug I/ConnectFragment: Address candidates are [**https://192.168.1.71:8096**, **http://192.168.1.71:8096**]

The `getRecommendedServers` method returns the following candidates that are ordered according to a score by protocol, port, response time, etc.

> 2021-05-07 22:55:04.990 18417-18417/org.jellyfin.mobile.debug I/ConnectFragment$checkServerUrlAndConnection$$inlined$collect: RecommendedServerInfo(address=https://192.168.1.71:8096, responseTime=142, score=GOOD, systemInfo=null, parent=null)
> 2021-05-07 22:55:05.134 18417-18417/org.jellyfin.mobile.debug I/ConnectFragment$checkServerUrlAndConnection$$inlined$collect: RecommendedServerInfo(address=http://192.168.1.71:8096, responseTime=138, score=OK, systemInfo=PublicSystemInfo(localAddress=http://192.168.1.71:8096, serverName=[REDACTED], version=10.7.5, productName=Jellyfin Server, operatingSystem=Windows, id=[REDACTED], startupWizardCompleted=true), parent=null)

Then `getRecommendedServer` method returns the candidate with the best score
> RecommendedServerInfo(address=https://192.168.1.71:8096, responseTime=142, score=GOOD, systemInfo=null, parent=null)

A reachable but invalid candidate [ERR_SSL_PROTOCOL_ERROR]

Workaround until proper fix in jellyfin-sdk-kotlin or whatever:

Replace

https://github.com/jellyfin/jellyfin-android/blob/382066d0643d636372dcc9c6c8579c481c9cf3eb/app/src/main/java/org/jellyfin/mobile/fragment/ConnectFragment.kt#L167

With

```
val recommendedServer = jellyfin.discovery.getRecommendedServers(candidates, false).firstOrNull {
    it.systemInfo != null
}
```

**Comment by solankimihir** [comment]
> RecommendedServerInfo(address=https://192.168.1.71:8096, responseTime=142, score=GOOD, systemInfo=null, parent=null)
> 
> A reachable but invalid candidate [ERR_SSL_PROTOCOL_ERROR]
> 

So if a user is entering an HTTPS address , it should work.
But if a user enters http address which is then processed by this sdk-function which validates it correctly, but returns an HTTPS address. Such HTTPS address is then used by the application to connect , which it obviously fails since HTTPS is not configured by the user, and hence the generic error of "Upgrade server version"?

**Comment by solankimihir** [comment]
> Not sure if this is useful information but I had this problem when I attempted to connect to the server directly i.e. via IP but it worked when I connected via my reverse proxy domain

Is it because you are using HTTPS when using reverse proxy domain, while the IP address uses HTTP?

**Comment by eltiel** [comment]
> > Not sure if this is useful information but I had this problem when I attempted to connect to the server directly i.e. via IP but it worked when I connected via my reverse proxy domain
> 
> Is it because you are using HTTPS when using reverse proxy domain, while the IP address uses HTTP?

Yes, this is the case

**Comment by nielsvanvelzen** [comment]
The error looks indeed to be related to the SDK not validating the response properly. I've already made changes for this yesterday. It will be added in a next beta version.

Here is an comparison of the changes when connecting to my local server. The input is "192.168.1.10" without protocol or port.

**New discovery code**
```
Starting discovery for 192.168.1.10
Found 5 candidates
https://192.168.1.10: BAD (replied in 2216ms, system information not found)
https://192.168.1.10:8096: BAD (replied in 31ms, system information not found)
https://192.168.1.10:8920: BAD (replied in 2029ms, system information not found)
http://192.168.1.10: BAD (replied in 2022ms, system information not found)
http://192.168.1.10:8096: GREAT (replied in 49ms, system information found)
```

**Old discovery code**
```
Starting discovery for 192.168.1.10
Found 5 candidates
https://192.168.1.10: OK (replied in 2226ms, system information not found)
https://192.168.1.10:8096: GOOD (replied in 31ms, system information not found)
https://192.168.1.10:8920: OK (replied in 2020ms, system information not found)
http://192.168.1.10: BAD (replied in 2059ms, system information not found)
http://192.168.1.10:8096: OK (replied in 2ms, system information found)
http://192.168.1.10:8096: OK (replied in 49ms, system information found)
```

**Comment by Zenopheus** [comment]
> 
> 
> > > Not sure if this is useful information but I had this problem when I attempted to connect to the server directly i.e. via IP but it worked when I connected via my reverse proxy domain
> > 
> > 
> > Is it because you are using HTTPS when using reverse proxy domain, while the IP address uses HTTP?
> 
> Yes, this is the case

I'm having the same problem with this beta. I'm using pfsense + haproxy and my jellyfin server is http. I've never been able to get the android clients to connect to my server through the proxy. The beta client produces the "version" error where as the older android versions  just say they can't connect. I'm hoping this change will finally get that working.

**Comment by Merlincool** [comment]
Still issue ain't fixed, I am getting error while getting connecting to Jellyfin server on my vps

**Comment by SweetthD3ViL** [comment]
Hello,

Updated to the latest Android beta version last night but I am unable to connect.

App version: [2.3.0-beta1]
Android version: [Android 11]
Device manufacturer and model: [Pixel 4a]
Jellyfin server version: [10.7.5]

I read the topic on reddit and the above messages. I am using the same url including http:// that on my browser but I am still unable to connect. 

And also tried my internal IP address without success.

**Comment by pyypgithub** [comment]
Got the same unsupported version error here with same URL that works in browser.

**Comment by nielsvanvelzen** [comment]
Please try again with the second beta release

**Comment by wjunker** [comment]
@nielsvanvelzen when will that be rolled out on play? Still getting release 1 of the beta :).

**Comment by nielsvanvelzen** [comment]
Second beta version is now released on the Play Store (F-Droid might take a while). This issue should be fixed, but if it's not please open a new issue.

**Comment by sunlight0258** [comment]
It’s already 2024, and the above reaction problem still exists. This is so surprising.

**Comment by ac11ca** [comment]
I'm still getting this problem, too.
