### ISSUE TITLE
Https/self signed certificate

### ISSUE THREAD

**Issue by MrNuggelz** [jellyfin/jellyfin-android#63]
I'm trying to connect to my server with a self signed ssl certificate, but I only get the "Connection Failure" screen. Connecting without ssl works.

**Comment by dkanada** [comment]
This is one of the features I had to remove while updating the codebase. I might have found a way to reimplement it [here](https://www.ibm.com/developerworks/community/blogs/mobileblog/entry/apache_cordova_working_with_certificates_on_android?lang=en_us) but considering the article is five years old it might not be working anymore. I will use this issue for tracking the feature.

**Comment by usntanon** [comment]
I'm not sure if this is related, but i cannot connect over SSL at all.  In any of the released betas.  I'm using an LE certificate via nginx reverse proxy.  Connects fine through the reverse proxy when not using SSL.

**Comment by JustAMan** [comment]
Did you provide https in url and port in separate field? In my experience if I provide non-empty port (in my case I tried putting 443 there) it won't connect, but leaving port empty works just fine. I'm using similar setup to you - ssl from LE and nginx as reverse proxy.

**Comment by usntanon** [comment]
I gave it a shot and popped "https://jelly.example.com" in the "Host" field and left the "Port" field blank.  Still saying it's unable to connect (with betas 1 through 4).  Using the web ui works well at home and remotely using the webui, but maybe i'm missing some special sauce in my nginx config.

**Comment by dkanada** [comment]
Could you guys check this on one of the newer versions? This should be working properly since beta5 or so if I recall correctly.

**Comment by MrNuggelz** [comment]
For me it didn't work on the beta7 version!

**Comment by NoShinSekai** [comment]
Hi, I still have problem with self signed SSL certificate, using NGINX reverse proxy and the android app.
Test was made under Beta 9 Version. Do you have any idea of what goes wrong exactly?

**Comment by thornbill** [comment]
It should be possible to install the self signed certificate by following this [guide](https://support.google.com/nexus/answer/2844832?hl=en). The Jellyfin app should then trust the user installed certificate.

**Comment by NoShinSekai** [comment]
@thornbill Still no connection after the installation of the cert in Android, whether it is with IP Adress or DDNS, with non-empty or blank port . The app only work without SSL. By the way, trying to connect without SSL give me some strange "bug" with account's password on JellyFin Server, but i'm still using 10.2.2. May this be the reason?

**Comment by LJ-Software** [comment]
I am having the same issue using a letencrypt certificate. Currently using v0.9.1 of the android app. I have tried using no port and 443 to no avail. Just as other's have mentioned, I am able to connect via the webapp from inside and outside my network using https. I appreciate the work.

**Comment by joelschwabe** [comment]
I'm still having this issue. My Jellyfin has a self signed cert, and I'm using nginx reverse proxy. My external port for access is not 443 however. When I'm trying to connect while on the same intranet while on wifi with the android app, I can connect fine (via IP and with http+port), but when I'm on the internet trying to connect with https and my dynamic dns name and port (10000ish level, I have 443 taken by something else), I immediately get the connection failure screen. I can connect with the same parameters using the web client on Vivaldi mobile and Firefox mobile, but the native Android App is still not working for me.

**Comment by JustAMan** [comment]
Same as #193. We have already explained why it happens and the reasons of why we won't probably be supporting this scenario in current implementation.
