### ISSUE TITLE
Exoplayer loading the wrong subtitle

### ISSUE THREAD

**Issue by zx900930** [jellyfin/jellyfin-android#944]
### Describe the bug

I'm facing this subtitle loading bug.

Subtitle settings:
![image](https://user-images.githubusercontent.com/734749/210184614-c30dafca-c9b7-4997-9af9-ad49a9c69a63.png)

The server correctly detect the chinese subtitles and use it to play the media
![image](https://user-images.githubusercontent.com/734749/210184765-a7fa6c4b-f474-4a70-bdec-39ef0a323c48.png)

As the logs shows below, the server send the file without subtitle index.
`[2023-01-01 20:58:32.617 +00:00] [INF] [45] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="Jellyfin Android", Path="/media/series/Romantic Killer/Season 1/Romantic Killer - S01E09 - Ginger Ale Is a Force Majeure WEBRip-1080p.mkv", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/2c8882d8-0158-68c7-6d25-6e0ac6b4c484/stream.mkv?MediaSourceId=2c8882d8015868c76d256e0ac6b4c484&Static=true&VideoCodec=hevc&AudioCodec=aac&AudioStreamIndex=3&api_key=<token>&Tag=8419c1b4b8e397a4fe5412e504ea7d35"`

Bug:
Exoplayer is playing the english subtitle despite the UI shows its a chinese subtitle (When I switched to english subtitle it displays chinese subtitle instead, the subtitle index was wrong).
![image](https://user-images.githubusercontent.com/734749/210184545-8e876d37-5615-42eb-a656-cca188ce36b3.png)

Media Info of the file:

```
Romantic Killer - S01E10 - Other Way Around, Dummy WEBRip-1080p
Container: mkv
Path: /media/series/Romantic Killer/Season 1/Romantic Killer - S01E10 - Other Way Around, Dummy WEBRip-1080p.mkv
Size: 433 MB

Video
Title: 1080p HEVC SDR
Codec: HEVC
Profile: Main 10
Level: 120
Resolution: 1920x1080
Aspect ratio: 16:9
Interlaced: No
Framerate: 23.976025
Bitrate: 2320 kbps
Bit depth: 10 bit
Video range: SDR
Video range type: SDR
Color space: bt709
Pixel format: yuv420p10le
Ref frames: 1

Audio
Title: Japanese - AAC - 5.1 - Default
Language: jpn
Codec: AAC
Profile: LC
Layout: 5.1
Channels: 6 ch
Bitrate: 207 kbps
Sample rate: 48000 Hz
Default: Yes
Forced: No
External: No

Subtitle
Title: 简体 - Chi - SUBRIP
Language: chi
Codec: SUBRIP
Default: No
Forced: No
External: No

Subtitle
Title: 繁体 - Chi - SUBRIP
Language: chi
Codec: SUBRIP
Default: No
Forced: No
External: No

Subtitle
Title: English - SUBRIP - External
Language: eng
Codec: SUBRIP
Default: No
Forced: No
External: Yes

Subtitle
Title: Fre - SUBRIP - External
Language: fre
Codec: SUBRIP
Default: No
Forced: No
External: Yes
```
 

The Web UI and desktop jellyfin media player doesn't have this bug.

For comparison:
Jellyfin media player or Web UI, the subtitle index was correct. 
![image](https://user-images.githubusercontent.com/734749/210184838-68cd252a-2aca-42ed-a038-82eddcf1d3c1.png)
And in the log you can clearly see the `SubtitleStreamIndex=4` is there
`[2023-01-01 21:17:10.980 +00:00] [INF] [8] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="Jellyfin Media Player", Path="/media/series/Romantic Killer/Season 1/Romantic Killer - S01E09 - Ginger Ale Is a Force Majeure WEBRip-1080p.mkv", AudioStreamIndex=3, SubtitleStreamIndex=4 ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/2c8882d8-0158-68c7-6d25-6e0ac6b4c484/stream.mkv?MediaSourceId=2c8882d8015868c76d256e0ac6b4c484&Static=true&VideoCodec=hevc&AudioCodec=aac&AudioStreamIndex=3&SubtitleStreamIndex=4&api_key=<token>&SubtitleMethod=Embed&Tag=8419c1b4b8e397a4fe5412e504ea7d35"`

### Logs

```shell
[2023-01-01 19:39:41.610 +00:00] [INF] [25] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="Jellyfin Android", Path="/media/series/Romantic Killer/Season 1/Romantic Killer - S01E09 - Ginger Ale Is a Force Majeure WEBRip-1080p.mkv", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/2c8882d8-0158-68c7-6d25-6e0ac6b4c484/stream.mkv?MediaSourceId=2c8882d8015868c76d256e0ac6b4c484&Static=true&VideoCodec=hevc&AudioCodec=aac&AudioStreamIndex=3&SubtitleStreamIndex=4&api_key=<token>&SubtitleMethod=Embed&Tag=8419c1b4b8e397a4fe5412e504ea7d35"
```

### Application version

2.4.4

### Where did you install the app from?

Google Play

### Device information

Lenovo XiaoXin Pad Pro 2021

### Android version

Android 11 OEM

### Jellyfin server version

10.8.8

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Maxr1998** [comment]
Could you try the 2.5.0-beta.1 please? We released that update the other day, it should contain a fix for your issue.

**Comment by zx900930** [comment]
> Could you try the 2.5.0-beta.1 please? We released that update the other day, it should contain a fix for your issue.

Still the same bug with 2.5.0-beta 1, and this bug only occurs when using  exoplayer since the web player is working correctly and external players doesnt auto load subs anyway.

**Comment by zikziko** [comment]
I'm currently facing the same issue.  2.5.0-beta 1 does not seem to resolve it. It seems like the player selects the subtitles next in line of the subtitles you select.

**Comment by Me0wzz** [comment]
I can also confirm that ExoPlayer loads other subtitle that I didn't select. When using Web based player, It loads subtitle flawlessly.
Server: 10.8.9 (docker)
App: 2.5.0-beta1

**Comment by mskpluk** [comment]
Not resolved in 2.5.0-beta2

**Comment by mskpluk** [comment]
Works as it should in 2.5.2

**Comment by uaevuon** [comment]
Still same on latest version.
